### ISSUE TITLE
Does subcollections() work?

### ISSUE THREAD

**Issue by cboulanger** [tnajdek/zotero-api-client#13]
Hi, probably I am doing something wrong, but I don't get subcollections to work:
```javascript
const api = require('zotero-api-client');
const lib1  = api(process.env.ZOT_API_KEY).library("user",12345);
(async ()=>{
  let response = await lib1.subcollections().get();
  let collectionData = response.getData();
  console.log(collectionData);
})();
```

Expected result: JSON data for only the top-level collections
Actual result: JSON data for 25 random collections

**Comment by tnajdek** [comment]
`subcollections` can only be used when requesting collections existing underneath another collection. In the example you've posted it should be rejected (but isn't because #2 is not yet implemented) since you haven't specified a parent collection.

For top-level collections, the correct keyword is `top`, I believe in your example it would be `lib1.collections().top().get()`.

An example where subcollections could be used, getting all subcollections living under a collection  with a key "AABBCCDD":

`lib1.collections("AABBCCDD").subcollections().get()`

**Comment by cboulanger** [comment]
Yes, this worked! Thanks so much for your quick response. It might make sense to update the [documentation on `subcollections()`](https://github.com/tnajdek/zotero-api-client#module_api--module.exports..subcollections) so that "Should only be used in conjuction with both library() ..." is not misunderstood.
