### ISSUE TITLE
Output from RawApiResponse?

### ISSUE THREAD

**Issue by bjohas** [tnajdek/zotero-api-client#4]
Hello - using the code here:
https://github.com/bjohas/ZoteroApiSimple/blob/master/app.js

The options would require reading a raw api response - how do I do that? (See 'RawApiResponse' in code above.)

Many thanks!

**Comment by tnajdek** [comment]
Hi,

I've looked at your code but I cannot see how would you ever receive a `RawApiResponse`, which is basically only used when `format` is set to something else than `json`. From what I've seen, both your api calls would return `MultiReadResponse`.

However seeing that you request additional formats ('bib, citation, coins' etc.) using `include`, I'm guessing that perhaps you're trying to access these? Currently extracting these would require manual mapping over the raw response (i.e. the actual response coming from the api, not to confuse with `RawApiResponse` which is a response type introduced by `zotero-api-client`).

Here is an example how to extract citations, based on your code:

````js
let response = await api().library('group', 2129771).items().top().get(options);
let citations = response.raw.map(r => 'citation' in r && r.citation || null);
````

Two things to note:

1. This will not work for `SingleReadResponse` because raw response there has different structure
1. `zotero-api-client` is considered in development and things are likely to change, in near future I'd expect something like `response.getCitations()` to return citations if available

**Comment by tnajdek** [comment]
Yes, that's correct `itemKey` options is used to search results for specific key or keys so it's used with queries that result MultiReadResponse. If you happen to provide only one key, it will return a MultiReadResult containing just one item (or zero items if that key was not found in requested set).
