### ISSUE TITLE
.items(item) seems to have no effect

### ISSUE THREAD

**Issue by bjohas** [tnajdek/zotero-api-client#5]
Perhaps I misunderstand the use of .items(item) - but it doesn't seem to narrow down the response to that item. What's the difference between .items('ABC') and options.itemKey = 'ABC' ?

**Comment by tnajdek** [comment]
Firstly, please bear in mind that `zotero-api-dev`, while it's mostly functional, is not considered complete (hence version 0.x). Some combinations of api requests should be rejected but are instead silently ignored or produce invalid requests to the api. This is why you might see a scenario where `.items(item)` seemingly does nothing. That is a known issue and is noted in #2.

`.items(item)` indicates that we will use `item` resource, meaning we will either want that item or something directly related to it.  This syntax is used for example when building a request for child items, the request to get all child items of `CG9H44U6` would look like this (using group from your code linked in #4 for this example):

````js
let response = await api().library('group', 2129771).items('CG9H44U6').children().get();
````

On the other hand `itemKey` is used when searching for specific item or items in a larger set, for example looking for 'CG9H44U6' and 'YXSZD8F3' in all the items within the group library:

````js
let response = await api().library('group', 2129771).items().get({ itemKey: ['CG9H44U6', 'YXSZD8F3'] })
````

Hope this answers your question. I'm closing this as the underlying issue is tracked as #2

**Comment by bjohas** [comment]
Many thanks for your comments - that's very helpful. Sure, appreciate it's in early stages!

For this query,
`let response = await api().library('group', 2129771).items('CG9H44U6').get();
`
you would expect one item to be returned?  Or several? I am expecting one (i.e. that one item), but maybe that's wrong?

I've updated the example here https://github.com/bjohas/ZoteroApiSimple/blob/master/app.js, and 
if you search for "If this is removed" it highlights the issue. 

Many thanks - this is really helpful!!

**Comment by tnajdek** [comment]
````js
let response = await api().library('group', 2129771).items('CG9H44U6').get();
````

will produce a `SingleReadResponse` containing data about `CG9H44U6` item.

Now regarding your code, you have:

````js
await api().library('group', group).collections(collection).items().top(item).get(options);
````

Firstly `top()` does not take an argument, so `top(item)` is invalid and will be silently ignored. It will work as `top()`. The entire query will request the **set of top-level items within a specific collection in the library**. If your options contains `itemKey`, it will further limit the results to just these items thus returning `MultiReadResponse` containign at most one item, that is your `q.item` but only if that key appears in the above mentioned set.

You also have:

````js
await api().library('group', group).items(item).top().get(options);
````

This will get **the set of all top-level items in the library** (technically excluding trashed items). Again If your options contains `itemKey`, it will further limit the results to just these items thus returning `MultiReadResponse` containign at most one item, that is your `q.item` but only if that key appears in the above mentioned set.

As you can see from the above, using `itemKey` limits your results just one item (if it's present in the requested set of items), hence producing the same result for both queries.

**Comment by bjohas** [comment]
Ah! I assumed that top won't matter!

This was the query I wanted:
`                response = await api().library('group', group).items(item).get(options);
`
So basically, if you specify .collections or .items or .top you'll always get a MultiRead, and item in .items(item) doesn't matter? 

However, if you only use .items(item), then you get that item as a SingleRead response.

Thanks again!
Bjoern
